
# Swap configs for samsung board
ifeq (y, $(filter y,\
	$(CONFIG_SEC_PLATFORM_B5Q) \
	$(CONFIG_SEC_PLATFORM_E5Q)))
    $(info "overwrite kalama as kalama_b5 config")
    $(shell rm -fr $(AUDIO_ROOT)/config/kalamaauto.conf)
    $(shell cp $(AUDIO_ROOT)/config/kalama_b5.conf $(AUDIO_ROOT)/config/kalamaauto.conf)
    $(shell rm -fr $(AUDIO_ROOT)/config/kalamaautoconf.h)
    $(shell cp $(AUDIO_ROOT)/config/kalamaautoconf_b5.h $(AUDIO_ROOT)/config/kalamaautoconf.h)
endif
