
# Swap configs for samsung board
ifeq (y, $(filter y,\
	$(CONFIG_SEC_PLATFORM_B5Q) \
	$(CONFIG_SEC_PLATFORM_E5Q)))
    $(info "overwrite kalama as kalama_b5 config")
    $(shell rm -fr $(AUDIO_ROOT)/config/kalamaauto.conf)
    $(shell cp $(AUDIO_ROOT)/config/kalama_b5.conf $(AUDIO_ROOT)/config/kalamaauto.conf)
    $(shell rm -fr $(AUDIO_ROOT)/config/kalamaautoconf.h)
    $(shell cp $(AUDIO_ROOT)/config/kalamaautoconf_b5.h $(AUDIO_ROOT)/config/kalamaautoconf.h)
endif

ifeq (y, $(filter y,\
	$(CONFIG_SEC_PLATFORM_GTS9) \
	$(CONFIG_SEC_PLATFORM_GTS9P) \
	$(CONFIG_SEC_PLATFORM_GTS9U) \
	$(CONFIG_SEC_PLATFORM_GTS9WIFI) \
	$(CONFIG_SEC_PLATFORM_GTS9PWIFI) \
	$(CONFIG_SEC_PLATFORM_GTS9UWIFI)))
    $(info "overwrite kalama as kalama_gts9 config")
    $(shell rm -fr $(AUDIO_ROOT)/config/kalamaauto.conf)
    $(shell cp $(AUDIO_ROOT)/config/kalama_gts9.conf $(AUDIO_ROOT)/config/kalamaauto.conf)
    $(shell rm -fr $(AUDIO_ROOT)/config/kalamaautoconf.h)
    $(shell cp $(AUDIO_ROOT)/config/kalamaautoconf_gts9.h $(AUDIO_ROOT)/config/kalamaautoconf.h)
endif

